package fmi.sports.tournament.organizer.backend.responses;

public enum ResponseResult {
    SUCCESSFULLY_CREATED,
    SUCCESSFULLY_UPDATED,
    SUCCESSFULLY_DELETED,
    SUCCESSFULLY_FOUND,
    TOURNAMENT_ALREADY_STARTED_OR_FINISHED,
    TEAM_ALREADY_REGISTERED,
    NO_MORE_PLACES_AVAILABLE,
    INSUFFICIENT_MONEY,
    SUCCESSFULLY_REGISTERED,
    SUCCESSFULLY_UNREGISTERED,
    ID_NOT_FOUND,
    SUCCESSFULLY_SCHEDULED,
    TEAM_NOT_PARTICIPATING_IN_TOURNAMENT,
    MATCH_ALREADY_COMPLETED,
    USER_ALREADY_EXISTS,
    NOT_EXISTING_USER,
    WRONG_PASSWORD,
    INVALID_REQUEST_DATA,
    VALID_TOKEN,
    USER_ALREADY_REGISTERED_FOR_TEAM,
    USER_NOT_IN_TEAM,
    SUCCESSFULLY_REMOVED_FROM_TEAM,
    USER_ALREADY_REGISTERED_FOR_ANOTHER_TEAM,
    SUCCESSFULLY_SIGNED_IN
}
